module.exports = {
  apps: [
    {
      name: 'telepharmacy-api',
      cwd: './apps/api',
      script: 'dist/main.js',
      instances: 'max',
      exec_mode: 'cluster',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      max_memory_restart: '512M',
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: 'telepharmacy-admin',
      cwd: './apps/admin',
      script: 'node_modules/.bin/next',
      args: 'start --port 3001',
      instances: 1,
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      max_memory_restart: '512M',
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'telepharmacy-shop',
      cwd: './apps/shop',
      script: 'node_modules/.bin/next',
      args: 'start --port 3002',
      instances: 1,
      env_production: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      max_memory_restart: '512M',
      error_file: './logs/shop-error.log',
      out_file: './logs/shop-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
