import { Injectable } from '@nestjs/common';
import { TelemedicineAuditService, AuditSearchFilters } from './audit.service';
import PDFDocument from 'pdfkit';

@Injectable()
export class AuditReportService {
  constructor(private readonly auditService: TelemedicineAuditService) {}

  /**
   * Generate PDF audit report with digital signature
   * Court-admissible format for regulatory compliance
   */
  async generatePdfReport(filters: AuditSearchFilters): Promise<Buffer> {
    const { logs, total } = await this.auditService.search({
      ...filters,
      limit: 1000, // Max entries per report
    });

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: 'Telemedicine Audit Trail Report',
          Author: 'LINE Telepharmacy System',
          Subject: 'Medical-Grade Audit Log',
          Keywords: 'audit, telemedicine, compliance, PDPA',
        },
      });

      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // Header
      doc
        .fontSize(20)
        .font('Helvetica-Bold')
        .text('Telemedicine Audit Trail Report', { align: 'center' });

      doc.moveDown();

      // Report metadata
      doc.fontSize(10).font('Helvetica');
      doc.text(`Generated: ${new Date().toLocaleString('th-TH')}`, { align: 'center' });
      doc.text(`Total Entries: ${total}`, { align: 'center' });

      if (filters.startDate || filters.endDate) {
        const dateRange = [
          filters.startDate?.toLocaleDateString('th-TH'),
          filters.endDate?.toLocaleDateString('th-TH'),
        ]
          .filter(Boolean)
          .join(' - ');
        doc.text(`Date Range: ${dateRange}`, { align: 'center' });
      }

      doc.moveDown(2);

      // Filters applied
      if (Object.keys(filters).length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('Filters Applied:');
        doc.fontSize(10).font('Helvetica');

        if (filters.actorId) doc.text(`Actor ID: ${filters.actorId}`);
        if (filters.actorType) doc.text(`Actor Type: ${filters.actorType}`);
        if (filters.actionType) doc.text(`Action Type: ${filters.actionType}`);
        if (filters.entityType) doc.text(`Entity Type: ${filters.entityType}`);
        if (filters.entityId) doc.text(`Entity ID: ${filters.entityId}`);

        doc.moveDown();
      }

      // Audit log entries
      doc.fontSize(12).font('Helvetica-Bold').text('Audit Log Entries:');
      doc.moveDown();

      logs.forEach((log, index) => {
        // Check if we need a new page
        if (doc.y > 700) {
          doc.addPage();
        }

        doc.fontSize(10).font('Helvetica-Bold').text(`Entry ${index + 1}:`);
        doc.fontSize(9).font('Helvetica');

        doc.text(`Timestamp: ${log.timestamp.toISOString()}`);
        doc.text(`Actor: ${log.actorType} (${log.actorId})`);
        doc.text(`Action: ${log.actionType}`);
        doc.text(`Entity: ${log.entityType} (${log.entityId})`);
        doc.text(`Hash: ${log.currentHash.substring(0, 16)}...`);

        if (log.ipAddress) {
          doc.text(`IP Address: ${log.ipAddress}`);
        }

        if (log.sessionId) {
          doc.text(`Session: ${log.sessionId}`);
        }

        doc.moveDown(0.5);
      });

      // Footer with digital signature notice
      doc.addPage();
      doc.fontSize(12).font('Helvetica-Bold').text('Certification', { align: 'center' });
      doc.moveDown();

      doc.fontSize(10).font('Helvetica').text(
        'This audit trail report is generated from an immutable, append-only log system ' +
          'with blockchain-inspired hash chaining for tamper detection. All entries are ' +
          'cryptographically signed using SHA-256 hashing algorithm.',
        { align: 'justify' },
      );

      doc.moveDown();

      doc.text(
        'The integrity of this audit trail can be independently verified using the ' +
          'hash chain verification API endpoint.',
        { align: 'justify' },
      );

      doc.moveDown(2);

      doc.text('Generated by: LINE Telepharmacy System', { align: 'center' });
      doc.text(`Report ID: ${this.generateReportId()}`, { align: 'center' });

      doc.end();
    });
  }

  private generateReportId(): string {
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substring(2, 8);
    return `RPT-${timestamp}-${random}`.toUpperCase();
  }
}
